version: 0.2

phases:
  build:
    commands:
      - docker build -t email_miner .
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
      - docker tag email_miner:<awr_ecr_arn>/email_miner:latest
      - docker push <awr_ecr_arn>/email_miner:latest
